[package]
name = "PersonalBlogEngine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"

diesel = { version = "1.4.4", features = ["sqlite", "r2d2", "chrono"] }
dotenv = "0.15.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
futures = "0.3"
chrono = { version = "0.4.19", features = ["serde"] }
actix-redis = "0.10"
actix-session = {version = "0.6", features = ["redis-actor-session"]}
actix-identity = "0.4"
argon2 = {version = "0.3", features = ["std"] }
rand_core = { version = "0.6", features = ["std"] }
comrak = "0.12"