version: "3"

services:
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "pbe"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/pbe
    restart: always
volumes:
  postgres-data: